name: Build DISK BASIC

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: "0 */6 * * *"

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-release:
    
    name: "Build and release"

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install
      run: sudo apt-get install nasm
    - name: Make
      run: make
    - name: Delete old release
      run: gh release delete "$(make get-version)" --cleanup-tag -y || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: gh release create -t "v$(make get-version)" "$(make get-version)" basic.img -n "Version \`$(make get-version)\` was built in this release"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
